### ISSUE TITLE
Proposal: Replace MAINTAINERS.d with maintainers.yaml

### ISSUE THREAD

**Issue by ermo** [getsolus/packages#1769]
To increase the ability to trivially parse and generate reports about package maintainers, I propose that we rewrite the current `MAINTAINERS.md` file to `maintainers.yaml`. The format I came up with looks like this and relies on so-called "yaml records":

```yaml
maintainers:
- Troy Harvey:
  email: redacted@redacted.com
  matrix: ~
  active: true
- A. WOL.:
  email: ~
  matrix: ~
  active: false
description: |
This file is used to indicate primary maintainership for this package. A package may list more than one maintainer to
avoid bus factor issues. People on this list may be considered “subject-matter experts”.

Please note that Solus staff may need to perform necessary rebuilds, upgrades, or security fixes as part of the normal
maintenance of the Solus package repository. 

If you believe this package requires an update, follow documentation from:

https://help.getsol.us/docs/packaging/procedures/request-a-package-update

In the event that this package becomes insufficiently maintained, the Solus staff reserves the right to request a new
maintainer, or deprecate and remove this package from the repository entirely.
```

I've added the `active:` key as a suggestion, so we have a way to gauge the effect of offboarding a maintainer and a way to enable maintainers to take a temporary leave of absence.

Thoughts welcome.

**Comment by ermo** [comment]
@davidjharder Assigning this to you so you can keep us on our toes re. helping to suss out our maintainer policies and how to monitor the state of the repo. Justin may have an idea or two here re. his package status PoC?

**Comment by TraceyC77** [comment]
@Justinzobel  - ping since ermo said you might have an idea regarding this

**Comment by ermo** [comment]
Harvey has a sed script PoC that can help do the MAINTAINERS.md conversion to `maintainers.yaml`:

https://gist.githubusercontent.com/HarveyDevel/8dacdf12cbf62e1d6c35921d18e5efb3/raw/bdddcd431ff8ec5588d35ff5bc0f4c1a62251952/convert2yaml.sh

**Comment by Justinzobel** [comment]
I would probably put Matrix handle first as reports about packages should be on the packages repo on GitHub. In Matrix they can easily get lost/forgotten.

**Comment by silkeh** [comment]
I like having a machine-readable format. However, I would prefer that we integrate with [CODEOWNERS](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners), as that has additional benefits in terms of automatic pings and PR review requests, approvals, etc.

Counter proposal:

- Have a `.github/CODEOWNERS` file that contains the maintainers for packages by their GitHub handle, eg:
  ```text
  # This file is used to indicate primary maintainership for packages. 
  # A package may list more than one maintainer to avoid bus factor issues.
  # People on this list may be considered “subject-matter experts”.
  # Please note that Solus staff may need to perform necessary rebuilds, upgrades, or security fixes as part of the normal maintenance of the Solus package repository. 
  # If you believe a package requires an update, follow documentation from: https://help.getsol.us/docs/packaging/procedures/request-a-package-update
  # In the event that this package becomes insufficiently maintained, the Solus staff reserves the right to request a new maintainer, or deprecate and remove this package from the repository entirely.
  packages/e/example/ @silkeh 
  ```
- Have a `common/maintainers.yaml` that provides a mapping of GitHub user names to contact details. For example:
  ```yaml
  # This file contains the contact information for all maintainers.
  # It ties in with the `.github/CODEOWNERS` file, which indicates 
  ---
  @silkeh :
    name: Silke Hofstra
    email: redacted@redacted.com
    matrix: ~
    active: true
  @<awol>:
    name: A. WOL.
    email: ~
    matrix: ~
    active: false
  ```
