### ISSUE TITLE
solus systemd[1]: Failed to start nvidia-powerd service.

### ISSUE THREAD

**Issue by FAb7D** [getsolus/packages#317]
### Summary

Not sure if it's a real bug, but the output of sudo systemctl status nvidia-powerd
is:
```
× nvidia-powerd.service - nvidia-powerd service
     Loaded: loaded (/usr/lib/systemd/system/nvidia-powerd.service; disabled; preset: enabled)
    Drop-In: /usr/lib64/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: failed (Result: exit-code) since Sun 2023-08-27 14:15:42 CEST; 2h 7min ago
    Process: 1031 ExecStart=/usr/bin/nvidia-powerd (code=exited, status=1/FAILURE)
   Main PID: 1031 (code=exited, status=1/FAILURE)
        CPU: 2ms

ago 27 14:15:42 solus systemd[1]: Starting nvidia-powerd service...
ago 27 14:15:42 solus /usr/bin/nvidia-powerd[1031]: nvidia-powerd version:1.0(build 1)
ago 27 14:15:42 solus /usr/bin/nvidia-powerd[1031]: SBIOS support not found for NVPCF GET_SUPPORTED fun>
ago 27 14:15:42 solus /usr/bin/nvidia-powerd[1031]: No matching GPU found
ago 27 14:15:42 solus /usr/bin/nvidia-powerd[1031]: Failed to initialize RM Client
ago 27 14:15:42 solus systemd[1]: nvidia-powerd.service: Main process exited, code=exited, status=1/FAI>
ago 27 14:15:42 solus systemd[1]: nvidia-powerd.service: Failed with result 'exit-code'.
ago 27 14:15:42 solus systemd[1]: Failed to start nvidia-powerd service.
```
my nvdia smi is:
```
nvidia-smi
Sun Aug 27 16:26:21 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.98                 Driver Version: 535.98       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1650        On  | 00000000:01:00.0  On |                  N/A |
| N/A   47C    P8               6W /  50W |    605MiB /  4096MiB |      1%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1126      G   /usr/lib64/xorg-server/Xorg                 325MiB |
|    0   N/A  N/A      1674      G   /usr/bin/budgie-wm                           46MiB |
|    0   N/A  N/A     22476      G   /usr/bin/firefox                            229MiB |
```

```
inxi -Gxx
Graphics:
  Device-1: Intel CoffeeLake-H GT2 [UHD Graphics 630] vendor: Hewlett-Packard
    driver: i915 v: kernel arch: Gen-9.5 ports: active: none off: eDP-1
    empty: DP-1,HDMI-A-1 bus-ID: 00:02.0 chip-ID: 8086:3e9b
  Device-2: NVIDIA TU117M [GeForce GTX 1650 Mobile / Max-Q]
    vendor: Hewlett-Packard driver: nvidia v: 535.98 arch: Turing pcie:
    speed: 2.5 GT/s lanes: 8 ports: active: none off: HDMI-A-2 empty: DP-2
    bus-ID: 01:00.0 chip-ID: 10de:1f91
  Device-3: Lite-On HP Wide Vision HD Camera driver: uvcvideo type: USB
    rev: 2.0 speed: 480 Mb/s lanes: 1 bus-ID: 1-5:3 chip-ID: 04ca:707f
  Display: x11 server: X.Org v: 1.20.14 with: Xwayland v: 23.1.2
    compositor: budgie-wm driver: X: loaded: modesetting,nvidia dri: iris
    gpu: i915,nvidia,nvidia-nvswitch display-ID: :0 screens: 1
  Screen-1: 0 s-res: 3840x2160 s-dpi: 96
  Monitor-1: HDMI-A-2 mapped: HDMI-0 note: disabled pos: primary
    model: BenQ PD2700U res: 3840x2160 dpi: 163 diag: 685mm (27")
  Monitor-2: eDP-1 mapped: eDP-1-1 note: disabled model: BOE Display 0x0852
    res: 3840x2160 dpi: 142 diag: 395mm (15.5")
  API: OpenGL v: 4.6.0 NVIDIA 535.98 renderer: NVIDIA GeForce GTX
    1650/PCIe/SSE2 direct-render: Yes
```

### Steps to reproduce

look at summary

### Expected result

look at summary

### Actual result

Failed to start nvidia-powerd service.

### Environment

- [ ] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Budgie

### System details

```
$  lspci
00:00.0 Host bridge: Intel Corporation 8th Gen Core Processor Host Bridge/DRAM Registers (rev 07)
00:01.0 PCI bridge: Intel Corporation 6th-10th Gen Core Processor PCIe Controller (x16) (rev 07)
00:02.0 VGA compatible controller: Intel Corporation CoffeeLake-H GT2 [UHD Graphics 630]
00:04.0 Signal processing controller: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Thermal Subsystem (rev 07)
00:08.0 System peripheral: Intel Corporation Xeon E3-1200 v5/v6 / E3-1500 v5 / 6th/7th/8th Gen Core Processor Gaussian Mixture Model
00:12.0 Signal processing controller: Intel Corporation Cannon Lake PCH Thermal Controller (rev 10)
00:14.0 USB controller: Intel Corporation Cannon Lake PCH USB 3.1 xHCI Host Controller (rev 10)
00:14.2 RAM memory: Intel Corporation Cannon Lake PCH Shared SRAM (rev 10)
00:15.0 Serial bus controller: Intel Corporation Cannon Lake PCH Serial IO I2C Controller #0 (rev 10)
00:16.0 Communication controller: Intel Corporation Cannon Lake PCH HECI Controller (rev 10)
00:17.0 RAID bus controller: Intel Corporation 82801 Mobile SATA Controller [RAID mode] (rev 10)
00:1d.0 PCI bridge: Intel Corporation Cannon Lake PCH PCI Express Root Port #9 (rev f0)
00:1d.5 PCI bridge: Intel Corporation Cannon Lake PCH PCI Express Root Port #14 (rev f0)
00:1d.6 PCI bridge: Intel Corporation Cannon Lake PCH PCI Express Root Port #15 (rev f0)
00:1d.7 PCI bridge: Intel Corporation Cannon Lake PCH PCI Express Root Port #16 (rev f0)
00:1f.0 ISA bridge: Intel Corporation HM470 Chipset LPC/eSPI Controller (rev 10)
00:1f.3 Audio device: Intel Corporation Cannon Lake PCH cAVS (rev 10)
00:1f.4 SMBus: Intel Corporation Cannon Lake PCH SMBus Controller (rev 10)
00:1f.5 Serial bus controller: Intel Corporation Cannon Lake PCH SPI Controller (rev 10)
01:00.0 VGA compatible controller: NVIDIA Corporation TU117M [GeForce GTX 1650 Mobile / Max-Q] (rev a1)
01:00.1 Audio device: NVIDIA Corporation Device 10fa (rev a1)
02:00.0 Non-Volatile memory controller: Phison Electronics Corporation E12 NVMe Controller (rev 01)
03:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 16)
04:00.0 Unassigned class [ff00]: Alcor Micro AU6625 PCI-E Flash card reader controller
05:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8822BE 802.11a/b/g/n/ac WiFi adapter

```
```
 neofetch
            -```````````                  fabio@solus 
          `-+/------------.`              ----------- 
       .---:mNo---------------.           OS: Solus x86_64 
     .-----yMMMy:---------------.         Host: HP Pavilion Gaming Laptop 15-dk0xxx 
   `------oMMMMMm/----------------`       Kernel: 6.4.11-251.current 
  .------/MMMMMMMN+----------------.      Uptime: 2 hours, 27 mins 
 .------/NMMMMMMMMm-+/--------------.     Packages: 2456 (eopkg), 66 (flatpak) 
`------/NMMMMMMMMMN-:mh/-------------`    Shell: bash 5.1.16 
.-----/NMMMMMMMMMMM:-+MMd//oso/:-----.    Resolution: 3840x2160 
-----/NMMMMMMMMMMMM+--mMMMh::smMmyo:--    DE: Budgie 10.8 
----+NMMMMMMMMMMMMMo--yMMMMNo-:yMMMMd/.   WM: Mutter(Budgie) 
.--oMMMMMMMMMMMMMMMy--yMMMMMMh:-yMMMy-`   Theme: Arc-Dark [GTK2/3] 
`-sMMMMMMMMMMMMMMMMh--dMMMMMMMd:/Ny+y.    Icons: Paper [GTK2/3] 
`-/+osyhhdmmNNMMMMMm-/MMMMMMMmh+/ohm+     Terminal: tilix 
  .------------:://+-/++++++oshddys:      CPU: Intel i7-9750H (12) @ 4.500GHz 
   -hhhhyyyyyyyyyyyhhhhddddhysssso-       GPU: Intel CoffeeLake-H GT2 [UHD Graphics 630] 
    `:ossssssyysssssssssssssssso:`        GPU: NVIDIA GeForce GTX 1650 Mobile / Max-Q 
      `:+ssssssssssssssssssss+-           Memory: 3357MiB / 15845MiB 
         `-/+ssssssssssso+/-`
              `.-----..`                                          
                                      
```
