### ISSUE TITLE
knotes: Update summary and description

### ISSUE THREAD

**Issue by TraceyC77** [getsolus/packages#3606]
### Please confirm there isn't already an existing package update request

- [X] I have searched through package update requests

### Name

KNotes

### Version

na

### Link to the release notes or announcement.

https://apps.kde.org/knotes/

### Reason for updating

The summary and description in package.yml is outdated and misleading. Currently it says:

```yaml
Summary             : Full featured note application
Description         : KNotes aims to be a useful and full featured notes application for the KDE project. It tries to be as fast and lightweight as possible although including some
                      advanced features.
```

It's actually a sticky note app. In the [appdata file from source](https://invent.kde.org/pim/knotes/-/blob/master/src/data/org.kde.knotes.appdata.xml):

```xml
  <summary>Sticky notes application</summary>
...
  <description>
    <p>
      KNotes is a program that lets you write the computer equivalent of sticky notes.
      The notes are saved automatically when you exit the program, and they display when you open the program.
    </p>
```
