### ISSUE TITLE
Solus 4.6 XFCE RC ISO: External command (eopkg ar) failed to finish

### ISSUE THREAD

**Issue by endumiuz** [getsolus/packages#4050]
### Please confirm there isn't an existing open bug report

- [X] I have searched open bugs for this issue

### Summary

The installation does not complete on really slow computers because of a too short timeout on the add-repo command.

### Steps to reproduce

1. Use a _slow_ computer
2. Boot 4.6 RC ISO
3. Try installing the OS

### Expected result

The installation should complete sucessfully.

### Actual result

At the post-install phase, the installation is aborted with this error message: 

```
2024-10-13 - 17:18:54 [1]:     ERROR: Installation failed: "External command failed to finish." 
2024-10-13 - 17:18:54 [6]:     .. - message: "External command failed to finish." 
2024-10-13 - 17:18:54 [6]:     .. - details: Command <i>/usr/bin/eopkg ar Solus https://cdn.getsol.us/repo/shannon/eopkg-index.xml.xz</i> failed to finish in 30 seconds.
There was no output from the command.
```
[Full log](https://github.com/user-attachments/files/17357550/fail.log)

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Xfce

### System details

```
System:
  Host: janerik-solus Kernel: 6.10.13-304.current arch: x86_64 bits: 64
  Desktop: Xfce v: 4.18.1 Distro: Solus 4.6 convergence
Machine:
  Type: Laptop System: Hewlett-Packard product: HP Pavilion TS 11 Notebook PC
    v: 0890100000305900000320100 serial: <superuser required>
  Mobo: Hewlett-Packard model: 2178 v: 33.0C serial: <superuser required>
    UEFI: Insyde v: F.03 date: 06/21/2013
CPU:
  Info: dual core AMD A4-1250 APU with Radeon HD Graphics [MCP] speed (MHz):
    avg: 799 min/max: 800/1000
Graphics:
  Device-1: Advanced Micro Devices [AMD/ATI] Kabini [Radeon HD 8210]
    driver: amdgpu v: kernel
  Device-2: Realtek HP Truevision HD driver: uvcvideo type: USB
  Display: x11 server: X.Org v: 21.1.13 with: Xwayland v: 24.1.3 driver:
    gpu: amdgpu resolution: 1366x768~60Hz
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 24.2.3 renderer: AMD
    Radeon HD 8210 (radeonsi kabini LLVM 18.1.8 DRM 3.57 6.10.13-304.current)
Network:
  Device-1: Realtek RTL810xE PCI Express Fast Ethernet driver: r8169
  Device-2: Ralink RT3290 Wireless 802.11n 1T/1R PCIe driver: rt2800pci
Drives:
  Local Storage: total: 465.76 GiB used: 5.99 GiB (1.3%)
Info:
  Memory: total: 4 GiB note: est. available: 3.3 GiB used: 935.1 MiB (27.7%)
  Processes: 165 Uptime: 4m Shell: Bash inxi: 3.3.36

```

### Other comments

I fixed it by increasing the timeout for the add-repo command in `/usr/share/calamares/modules/shellprocess_postinstall.conf`:

```
# Reference: https://github.com/calamares/calamares/blob/3.2.x-stable/src/modules/shellprocess/shellprocess.conf

# To be ran post installation
---

dontChroot: false

script:
    - command: "/usr/sbin/usysconf run"
      timeout: 300

    # Add a comment to the vconsole conf about how to change the font in the future
    - "echo \"## The default console font on Solus is ter-v32b, if you would like to change that uncomment this and set it to your selection\" >> /etc/vconsole.conf"
    - "echo \"# FONT=ter-v32b\" >> /etc/vconsole.conf"

    # If the ISO was generated from unstable then remove the local repo and switch back to shannon
    # TODO: We could make a UI to configure this. Perhaps an advanced option to make the installed system run from unstable?
    - "/usr/bin/eopkg rr Local || true"

    - command: "/usr/bin/eopkg ar Solus https://cdn.getsol.us/repo/shannon/eopkg-index.xml.xz"
      timeout: 60

i18n:
    name: "Running post install triggers"
```

You probably want to set it to 300 seconds to match the other timeout values.

Edit:
After editing that file, the installation was completed successfully. [Here](https://github.com/user-attachments/files/17357836/sucess.log) you can see that the command took 37 seconds on this computer.
