### ISSUE TITLE
CI: Add ability to exempt a list of packages from the monitoring.yml check warning

### ISSUE THREAD

**Issue by HarveyDevel** [getsolus/packages#4533]
#### Suggested change.

We need a way to exempt packages from this warning just like we do for static libs.

#### Why?

Some packages do not benefit from having a monitoring.yml

Example:
`ffmpeg-chromium` is locked to the major Chromium version `vivaldi-snapshot` is currently using. The fact a new major is out isn't useful as what they updated to and when is up to the individual browsers and they must be updated together. More details on how this is updated [here](https://github.com/getsolus/packages/tree/main/packages/f/ffmpeg-chromium).

#### Known packages where a monitoring.yml will never be needed.

- `appstream-data`
- `ffmpeg-chromium`
- `ffmpeg-chromium-vivaldi-stable`
- `ffmpeg-chromium-opera`

**Comment by ermo** [comment]
@silkeh I know you're pretty busy rn and don't have a lot of free time.

But if at some point this changes, this issue would be high on the list of things that would make a difference to staff. Thanks. ^^'

**Comment by silkeh** [comment]
Maybe it would be clearer to add `monitoring.yml` files to these packages anyway? That would be a nice place to have an explanatory comment, and prevents other contributors from being confused that a very limited number of packages don't have `monitoring.yml`.

**Comment by HarveyDevel** [comment]
Fair enough, I thought an Anitya ID was mandatory but I checked and noticed a few packages already have a monitoring.yml without an id so I guess its fine.

Just add something like this instead?

```
# This package will never benefit from a monitoring.yml please do not attempt to edit any of the fields.
# Link to this issue (maybe?).
releases:
  id: ~
  rss: ~
# No known CPE, checked 2024-12-12
security:
  cpe: ~
```
