### ISSUE TITLE
gamescope non-functional on Nvidia systems

### ISSUE THREAD

**Issue by sturnclaw** [getsolus/packages#869]
### Summary

Valve `gamescope` is non-functional on my Nvidia hardware. A window is created for the application running inside gamescope, but no video is displayed in that window and the application hangs when attempting to present a frame.

### Steps to reproduce

1. Install `gamescope` 3.13.8+
2. Run `gamescope -- glxgears`
3. Observe no video output into the window gamescope creates
4. Clicking the close button or pressing Ctrl+C in the terminal forwards the signal to the client application but is never received
5. `pkill -9 gamescope-wl` is required to close the window, at which point the client application terminates due to either forwarded signals or a missing X server connection

### Expected result

Video frames to be displayed in the `gamescope` window, the running application to close when I click close on the window.

### Actual result

See reproduction steps above for summary.

### Environment

- [X] Is system up to date?

### Repo

Shannon (stable)

### Desktop Environment

Budgie

### System details

```
CPU: 8-core AMD Ryzen 7 5800X (-MT MCP-) speed/min/max: 2274/2200/4850 MHz
Kernel: 6.5.11-263.current x86_64 Up: 2h 4m Mem: 4.88/31.26 GiB (15.6%)
Storage: 3.18 TiB (75.7% used) Procs: 399 Shell: Bash inxi: 3.3.31

Graphics:
  Device-1: NVIDIA TU104 [GeForce RTX 2070 SUPER] driver: nvidia v: 535.129.03
  Display: x11 server: X.Org v: 21.1.9 with: Xwayland v: 23.2.2 driver: X:
    loaded: nvidia gpu: nvidia,nvidia-nvswitch resolution: 1: 1920x1080~60Hz
    2: 1920x1080~60Hz
  API: EGL Message: No EGL data available.
  API: OpenGL v: 4.6.0 vendor: nvidia v: 535.129.03 renderer: NVIDIA
    GeForce RTX 2070 SUPER/PCIe/SSE2
  API: Vulkan v: 1.3.261 drivers: nvidia,llvmpipe surfaces: xcb,xlib

Budgie Version: 10.8.2
```

### Other comments

I expect this to be an upstream issue - gamescope stability on Nvidia is not a primary target. 3.12.5 was confirmed to be the last known-good version, though it still had several defects and exhibited the same behavior when the client application launched in fullscreen mode as opposed to windowed.
